apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bacteria
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/howcansheslap/bacteria-frontend:1.0.5
        command:
          - npm
          - run
          - start-prod
        ports:
        - containerPort: 9003

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: bacteria
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9003

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: bacteria
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - bacteria.alsabagtech.com
    secretName: tls-secret2
  rules:
  - host: bacteria.alsabagtech.com
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80
        path: /(.*)
