version: '3'
 
services:
  frontend:
    depends_on:
      - backend
    build:
      context: ./bacteria-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "9003:9003"
    links:
      - backend
    networks:
      - main-service
  backend:
    command: ./main --db_host=db --db_port=3306
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "9002:9002"
    links:
      - db
    networks:
      - main-service
  db:
    image: mysql:5
    container_name: db
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: testroot
      MYSQL_DATABASE: bacteria
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "9001:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - main-service
networks:
  main-service:
