version: '3'
 
services:
  db:
    image: mysql:5
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: testroot
      MYSQL_DATABASE: bacteria
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "9001:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d