apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: bacteria
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: docker.io/howcansheslap/bacteria-backend:1.0.0
        command:
          - ./main
          - --db_host=db
          - --db_port=9001
        ports:
        - containerPort: 9002

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: bacteria
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9002

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: bacteria
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - bacteria-backend.alsabagtech.com
    secretName: tls-secret
  rules:
  - host: bacteria-backend.alsabagtech.com
    http:
      paths:
      - backend:
          serviceName: backend
          servicePort: 80
        path: /(.*)

