FROM golang:1.14 AS builder



WORKDIR /go/src/app
COPY . .

RUN go get -d -v ./...
RUN go install -v ./...
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o main .
CMD ["./main"]
# FROM alpine:latest
# COPY --from=builder /go/src/app/main /app/
# WORKDIR /app
# CMD ["./main"]